### ISSUE TITLE
[bug] convert_crs seems not to work with pp3.0

### ISSUE THREAD

**Issue by HaiQ31** [e2nIEE/pandapower#2607]
### Bug report checklis

- [x] Searched the [issues page](https://github.com/e2nIEE/pandapower/issues) for similar reports

- [x] Read the relevant sections of the [documentation](https://pandapower.readthedocs.io/en/latest/about.html)

- [x] Browse the [tutorials](https://github.com/e2nIEE/pandapower/tree/develop/tutorials) and [tests](https://github.com/e2nIEE/pandapower/tree/develop/pandapower/test) for usefull code snippets and examples of use

- [x] Reproduced the issue after updating with `pip install --upgrade pandapower` (or `git pull`)

- [x] Tried basic troubleshooting (if a bug/error) like restarting the interpreter and checking the pythonpath

### Reproducible Example

```python
import pandapower as pp
net = pp.create.create_empty_network("crs_test")
pp.create_bus(net,10.0,geodata=(1,1))
pp.plotting.geo.convert_crs(net,'epsg:25832')
```

### Issue Description and Traceback

Running the code above in pp 2.14.11 works but throws an Error on pp3.0:

```
  File "/<>/python3.11/site-packages/pandapower/plotting/geo.py", line 276, in convert_crs
    net.bus_geodata = net.bus_geodata.apply(lambda r: _geo_node_transformer(r), axis=1)
                      ^^^^^^^^^^^^^^^
  File "/<>/python3.11/site-packages/pandapower/auxiliary.py", line 251, in __getattr__
    raise AttributeError(
AttributeError: 'pandapowerNet' instance has no attribute 'bus_geodata'
```
If I got it right, [convert_crs](https://github.com/e2nIEE/pandapower/blob/5927f5b7c399978a1a38daf4d33d9031da19360e/pandapower/plotting/geo.py#L234) checks [whether `net.bus.geo` exists](https://github.com/e2nIEE/pandapower/blob/5927f5b7c399978a1a38daf4d33d9031da19360e/pandapower/plotting/geo.py#L252) but does [not use it](https://github.com/e2nIEE/pandapower/blob/5927f5b7c399978a1a38daf4d33d9031da19360e/pandapower/plotting/geo.py#L276) afterwards.

### Expected Behavior

convert_crs runs without errors and converts the content of `<element>.geo` to the desired projection

### Installed Versions

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.11.0.final.0
python-bits           : 64
OS                    : Darwin
OS-release            : 24.4.0
Version               : Darwin Kernel Version 24.4.0: Fri Apr 11 18:33:47 PDT 2025; root:xnu-11417.101.15~117/RELEASE_ARM64_T6000
machine               : arm64
processor             : arm
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : de_DE.UTF-8
pandas                : 2.2.2
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0.post0
setuptools            : 80.4.0
pip                   : 24.1.2
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : 5.4.0
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : None
IPython               : None
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : 3.10.3
numba                 : 0.60.0
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : None
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.13.1
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

### Label

- [x] Relevant labels are selected
